# Generation

This notebook builds timeline data and renders GIF outputs. For large datasets, render one GIF per day instead of one full-timeline GIF.

In [1]:
from pathlib import Path
from types import SimpleNamespace
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import Image as DisplayImage, display

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
SRC_DIR = PROJECT_ROOT / 'src'
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import config
from timeline import build_timeline
from animate_timeline import build_animation, build_daily_animations

In [2]:
timeline_args = SimpleNamespace(
    input_csv=config.INTEGRATED_OBJECTS_CSV,
    output_csv=config.OBJECT_TIMELINE_CSV,
)

timeline_rows = build_timeline(timeline_args)
len(timeline_rows), timeline_rows[:3]

(69933,
 [{'image_name': 'IR_57327.jpg',
   'timestamp': '2025-04-23 13:28:31',
   'detection_index': '4',
   'label': 'Machine',
   'people_or_machine': 'machine',
   'object_id': 'machine_2',
   'canonical_label': 'Machine',
   'merge_role': 'keep',
   'bbox_x0': '103.119843',
   'bbox_y0': '175.158752',
   'bbox_x1': '145.050507',
   'bbox_y1': '270.151733',
   'projected_x': '6.725138',
   'projected_y': '0.443425',
   'anchor_x': '6.476916',
   'anchor_y': '0.453659',
   'display_x': '6.476916',
   'display_y': '0.453659',
   'position_source': 'dbscan_machine_global_median_anchor',
   'static_cluster_id': 'dbscan_machine_0000',
   'clustering_method': 'dbscan_machine',
   'temp_mean_c': '25.472376',
   'temp_max_c': '31.236292'},
  {'image_name': 'IR_57327.jpg',
   'timestamp': '2025-04-23 13:28:31',
   'detection_index': '5',
   'label': 'Person',
   'people_or_machine': 'person',
   'object_id': 'person_frame_00003',
   'canonical_label': 'Person',
   'merge_role': 'keep',
   'bbox_x0': '97.701965',
   'bbox_y0': '40.435791',
   'bbox_x1': '206.714142',
   'bbox_y1': '181.041168',
   'projected_x': '3.843554',
   'projected_y': '1.269117',
   'anchor_x': '3.843554',
   'anchor_y': '1.269117',
   'display_x': '3.843554',
   'display_y': '1.269117',
   'position_source': 'frame_projection',
   'static_cluster_id': '',
   'clustering_method': 'none_person',
   'temp_mean_c': '23.292946',
   'temp_max_c': '34.000000'},
  {'image_name': 'IR_57327.jpg',
   'timestamp': '2025-04-23 13:28:31',
   'detection_index': '6',
   'label': 'Person',
   'people_or_machine': 'person',
   'object_id': 'person_frame_00004',
   'canonical_label': 'Person',
   'merge_role': 'keep',
   'bbox_x0': '332.459656',
   'bbox_y0': '133.982178',
   'bbox_x1': '405.665588',
   'bbox_y1': '276.657410',
   'projected_x': '5.619198',
   'projected_y': '3.056591',
   'anchor_x': '5.619198',
   'anchor_y': '3.056591',
   'display_x': '5.619198',
   'display_y': '3.056591',
   'position_source': 'frame_projection',
   'static_cluster_id': '',
   'clustering_method': 'none_person',
   'temp_mean_c': '23.366373',
   'temp_max_c': '34.000000'}])

In [3]:
'''
RUN_DAILY_ANIMATION = True
DISPLAY_FIRST_GIF = False  # Rendering GIFs inside Jupyter can be heavy; keep this False for full runs.

animation_args = SimpleNamespace(
    input_csv=config.OBJECT_TIMELINE_CSV,
    layout=config.LAYOUT_IMAGE,
    output=config.TIMELINE_GIF,
    daily_output_dir=config.DAILY_ANIMATION_OUTPUT_DIR,
    map_width=15.0,
    map_height=12.0,
    fps=4,
    temperature_column='temp_mean_c',
    machine_min_observations=2,
    people_min_observations=1,
    max_frames=None,
    day=None,
    split_by_day=True,
)

if RUN_DAILY_ANIMATION:
    gif_paths = build_daily_animations(animation_args)
    print(f"Generated {len(gif_paths)} daily GIFs")
    for path in gif_paths:
        print(path)
    if DISPLAY_FIRST_GIF and gif_paths:
        display(DisplayImage(filename=str(gif_paths[0])))
else:
    print('Daily animation not rendered. Set RUN_DAILY_ANIMATION = True to generate daily GIFs.')

'''

'\nRUN_DAILY_ANIMATION = True\nDISPLAY_FIRST_GIF = False  # Rendering GIFs inside Jupyter can be heavy; keep this False for full runs.\n\nanimation_args = SimpleNamespace(\n    input_csv=config.OBJECT_TIMELINE_CSV,\n    layout=config.LAYOUT_IMAGE,\n    output=config.TIMELINE_GIF,\n    daily_output_dir=config.DAILY_ANIMATION_OUTPUT_DIR,\n    map_width=15.0,\n    map_height=12.0,\n    fps=4,\n    temperature_column=\'temp_mean_c\',\n    machine_min_observations=2,\n    people_min_observations=1,\n    max_frames=None,\n    day=None,\n    split_by_day=True,\n)\n\nif RUN_DAILY_ANIMATION:\n    gif_paths = build_daily_animations(animation_args)\n    print(f"Generated {len(gif_paths)} daily GIFs")\n    for path in gif_paths:\n        print(path)\n    if DISPLAY_FIRST_GIF and gif_paths:\n        display(DisplayImage(filename=str(gif_paths[0])))\nelse:\n    print(\'Daily animation not rendered. Set RUN_DAILY_ANIMATION = True to generate daily GIFs.\')\n\n'

## Timeline Quality Debug

Use this area after rebuilding the timeline to check whether a 07 spike already exists in the 06 timeline CSV. It checks per-object/per-day temperature jumps, duplicate timestamps, long gaps, and source rows from the 05 integrated CSV.

In [4]:
TIMELINE_TEMP_COLUMN = 'temp_mean_c'
JUMP_THRESHOLD_C = 1.0
GAP_THRESHOLD_MIN = 5.0

quality_df = pd.read_csv(config.OBJECT_TIMELINE_CSV)
quality_df['timestamp_dt'] = pd.to_datetime(quality_df['timestamp'])
quality_df[TIMELINE_TEMP_COLUMN] = pd.to_numeric(quality_df[TIMELINE_TEMP_COLUMN], errors='coerce')
quality_static = quality_df[quality_df['people_or_machine'] == 'machine'].copy()
quality_static['date'] = quality_static['timestamp_dt'].dt.date.astype(str)
quality_static = quality_static.sort_values(['object_id', 'timestamp_dt'])
quality_static['temp_delta_c'] = quality_static.groupby('object_id')[TIMELINE_TEMP_COLUMN].diff()
quality_static['abs_temp_delta_c'] = quality_static['temp_delta_c'].abs()
quality_static['gap_min'] = quality_static.groupby('object_id')['timestamp_dt'].diff().dt.total_seconds() / 60.0

def p95(series):
    series = series.dropna()
    return series.quantile(0.95) if len(series) else np.nan

object_day_quality = (
    quality_static
    .groupby(['date', 'object_id', 'canonical_label'], dropna=False)
    .agg(
        rows=(TIMELINE_TEMP_COLUMN, 'size'),
        unique_timestamps=('timestamp_dt', 'nunique'),
        temp_min_c=(TIMELINE_TEMP_COLUMN, 'min'),
        temp_max_c=(TIMELINE_TEMP_COLUMN, 'max'),
        temp_range_c=(TIMELINE_TEMP_COLUMN, lambda s: s.max() - s.min()),
        max_abs_delta_c=('abs_temp_delta_c', 'max'),
        p95_abs_delta_c=('abs_temp_delta_c', p95),
        max_gap_min=('gap_min', 'max'),
    )
    .reset_index()
)
object_day_quality['duplicate_timestamp_rows'] = object_day_quality['rows'] - object_day_quality['unique_timestamps']
object_day_quality = object_day_quality.sort_values(['max_abs_delta_c', 'temp_range_c'], ascending=False)
display(object_day_quality.head(30))

,date,object_id,canonical_label,rows,unique_timestamps,temp_min_c,temp_max_c,temp_range_c,max_abs_delta_c,p95_abs_delta_c,max_gap_min,duplicate_timestamp_rows
76,2025-05-01,screen_1,Screen,985,984,21.312052,28.809393,7.497341,4.949690,1.271038,1035.016667,1
106,2025-05-07,cableduct_4,Cableduct,875,873,21.503016,27.153057,5.650041,4.645969,1.232100,940.033333,2
50,2025-04-29,screen_1,Screen,1227,1100,21.325386,27.434917,6.109531,4.392540,1.633965,5235.050000,127
29,2025-04-25,cableduct_3,Cableduct,1549,827,19.590124,26.060154,6.470030,4.302942,0.836563,978.833333,722
51,2025-04-29,screen_2,Screen,1011,1011,20.728750,25.833685,5.104935,4.199076,0.768914,5235.050000,0
93,2025-05-06,cableduct_3,Cableduct,423,338,21.193510,26.510857,5.317347,4.172593,1.159821,5123.833333,85
41,2025-04-29,cableduct_3,Cableduct,600,495,21.391724,25.390348,3.998624,4.094329,0.964068,5328.483333,105
88,2025-05-02,screen_1,Screen,914,914,21.181215,26.790165,5.608950,4.033272,1.317981,987.550000,0
101,2025-05-06,screen_2,Screen,506,506,20.897305,26.547829,5.650524,4.002335,0.894718,5125.350000,0
105,2025-05-07,cableduct_3,Cableduct,1061,742,20.932367,26.231953,5.299586,3.902060,1.130413,939.516667,319
11,2025-04-23,screen_2,Screen,956,956,20.359421,24.963774,4.604353,3.801333,0.383942,2.500000,0
32,2025-04-25,machine_2,Machine,872,871,19.771936,23.394846,3.622910,3.789547,1.097330,978.833333,1
37,2025-04-25,screen_2,Screen,934,934,19.847033,24.711906,4.864873,3.768783,1.101518,979.333333,0
42,2025-04-29,cableduct_4,Cableduct,645,644,21.835150,26.301205,4.466055,3.738127,1.119529,5357.983333,1
78,2025-05-01,window_1,Window,36,36,21.876734,25.901764,4.025030,3.727974,2.628350,1080.033333,0
77,2025-05-01,screen_2,Screen,825,825,20.891689,25.503073,4.611384,3.709332,0.648776,1035.016667,0
28,2025-04-25,cableduct_2,Cableduct,964,898,19.719055,24.697624,4.978569,3.704954,1.206672,989.850000,66
30,2025-04-25,cableduct_4,Cableduct,892,889,19.838238,25.400070,5.561832,3.689321,1.113738,979.850000,3
16,2025-04-24,cableduct_4,Cableduct,944,939,21.472029,26.330284,4.858255,3.611999,1.068950,538.233333,5
96,2025-05-06,machine_2,Machine,606,599,21.539309,26.773849,5.234540,3.512933,1.402708,5123.833333,7
114,2025-05-07,screen_2,Screen,680,680,20.588356,24.757759,4.169403,3.508312,1.079339,941.033333,0
104,2025-05-07,cableduct_2,Cableduct,739,692,20.842541,25.476944,4.634403,3.460215,1.328709,942.050000,47
90,2025-05-02,window_1,Window,66,66,21.395819,25.125568,3.729749,3.423933,0.935296,1093.033333,0
12,2025-04-23,window_1,Window,537,537,20.085569,24.752062,4.666493,3.382151,0.547826,84.500000,0
108,2025-05-07,machine_2,Machine,619,619,20.531816,24.313900,3.782084,3.311260,1.023441,939.516667,0
68,2025-05-01,cableduct_2,Cableduct,622,617,21.172533,25.314684,4.142151,3.260811,1.357922,1102.033333,5
13,2025-04-24,cableduct_1,Cableduct,902,900,20.415874,25.005791,4.589917,3.235699,1.082367,538.233333,2
92,2025-05-06,cableduct_2,Cableduct,235,217,21.226233,26.296776,5.070543,3.192398,1.403369,5125.850000,18
19,2025-04-24,machine_2,Machine,895,868,20.557932,26.416235,5.858303,3.138403,1.700769,538.233333,27
0,2025-04-23,cableduct_1,Cableduct,979,979,20.469877,23.828302,3.358425,3.101892,0.363749,2.500000,0

In [5]:
# Detailed check for the object/date that looks strange in 07.
DEBUG_OBJECT_ID = 'cableduct_2'
DEBUG_DATE = '2025-04-25'
DEBUG_TOP_N = 30

object_day = quality_static[
    (quality_static['object_id'] == DEBUG_OBJECT_ID) &
    (quality_static['date'] == DEBUG_DATE)
].sort_values('timestamp_dt').copy()

print(f"{DEBUG_DATE} | {DEBUG_OBJECT_ID} rows: {len(object_day)}")
print(f"unique timestamps: {object_day['timestamp_dt'].nunique()}")
if len(object_day):
    print(f"temp range: {object_day[TIMELINE_TEMP_COLUMN].min():.3f} to {object_day[TIMELINE_TEMP_COLUMN].max():.3f} C")
    print(f"max abs delta: {object_day['abs_temp_delta_c'].max():.3f} C")
    print(f"max gap: {object_day['gap_min'].max():.2f} min")

fig, ax = plt.subplots(figsize=(13, 4.5))
ax.plot(object_day['timestamp_dt'], object_day[TIMELINE_TEMP_COLUMN], color='#1f77b4', linewidth=1.4, label=TIMELINE_TEMP_COLUMN)
jump_rows = object_day[object_day['abs_temp_delta_c'] >= JUMP_THRESHOLD_C]
if not jump_rows.empty:
    ax.scatter(jump_rows['timestamp_dt'], jump_rows[TIMELINE_TEMP_COLUMN], color='red', s=32, label=f'jump >= {JUMP_THRESHOLD_C} C')
ax.set_title(f'{DEBUG_DATE} | {DEBUG_OBJECT_ID} timeline temperature check')
ax.set_xlabel('Timestamp')
ax.set_ylabel('Temperature (C)')
ax.grid(alpha=0.25)
ax.legend(loc='best')
fig.autofmt_xdate(rotation=25)
fig.tight_layout()

inspect_cols = [
    'timestamp_dt', 'timestamp', 'image_name', 'detection_index', 'label', 'canonical_label', 'object_id',
    'temp_mean_c', 'temp_max_c', 'temp_delta_c', 'abs_temp_delta_c', 'gap_min',
    'projected_x', 'projected_y', 'anchor_x', 'anchor_y', 'display_x', 'display_y',
    'position_source', 'static_cluster_id', 'clustering_method',
]
inspect_cols = [col for col in inspect_cols if col in object_day.columns]
print('Largest jumps:')
display(object_day.sort_values('abs_temp_delta_c', ascending=False)[inspect_cols].head(DEBUG_TOP_N))
print('Hottest rows:')
display(object_day.sort_values(TIMELINE_TEMP_COLUMN, ascending=False)[inspect_cols].head(DEBUG_TOP_N))

2025-04-25 | cableduct_2 rows: 964
unique timestamps: 898
temp range: 19.719 to 24.698 C
max abs delta: 3.705 C
max gap: 989.85 min
Largest jumps:

,timestamp_dt,timestamp,image_name,detection_index,label,canonical_label,object_id,temp_mean_c,temp_max_c,temp_delta_c,...,gap_min,projected_x,projected_y,anchor_x,anchor_y,display_x,display_y,position_source,static_cluster_id,clustering_method
21284,2025-04-25 07:35:39,2025-04-25 07:35:39,IR_59349.jpg,5,Cableduct,Cableduct,cableduct_2,19.790119,22.299999,-3.704954,...,989.850000,9.105911,2.837789,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28207,2025-04-25 13:53:09,2025-04-25 13:53:09,IR_60104.jpg,6,Cableduct,Cableduct,cableduct_2,21.286543,23.900000,-3.168611,...,0.516667,7.239231,3.327463,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27896,2025-04-25 13:33:39,2025-04-25 13:33:39,IR_60065.jpg,10,Cableduct,Cableduct,cableduct_2,22.031336,27.400000,-2.544208,...,1.016667,7.460018,3.405265,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28704,2025-04-25 14:22:09,2025-04-25 14:22:09,IR_60162.jpg,7,Cableduct,Cableduct,cableduct_2,21.291300,24.100000,-2.519813,...,0.500000,7.453705,3.400092,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27799,2025-04-25 13:27:38,2025-04-25 13:27:38,IR_60053.jpg,6,Cableduct,Cableduct,cableduct_2,24.558969,33.200001,2.443660,...,0.500000,7.338344,3.350806,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28285,2025-04-25 13:57:39,2025-04-25 13:57:39,IR_60113.jpg,6,Cableduct,Cableduct,cableduct_2,21.465883,24.000000,-2.178835,...,0.516667,7.307934,3.339446,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28055,2025-04-25 13:43:39,2025-04-25 13:43:39,IR_60085.jpg,3,Cableduct,Cableduct,cableduct_2,22.009373,26.700001,-2.109251,...,0.500000,7.281390,3.346290,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
26953,2025-04-25 12:33:09,2025-04-25 12:33:09,IR_59944.jpg,6,Cableduct,Cableduct,cableduct_2,21.848385,29.200001,-2.091236,...,1.000000,5.510767,2.250796,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
24556,2025-04-25 10:17:39,2025-04-25 10:17:39,IR_59673.jpg,5,Cableduct,Cableduct,cableduct_2,23.445864,26.600000,2.079485,...,0.500000,4.810170,2.207242,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28199,2025-04-25 13:52:38,2025-04-25 13:52:38,IR_60103.jpg,10,Cableduct,Cableduct,cableduct_2,24.455154,27.799999,2.067308,...,0.000000,6.356072,2.256669,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28018,2025-04-25 13:41:39,2025-04-25 13:41:39,IR_60081.jpg,5,Cableduct,Cableduct,cableduct_2,22.640392,27.500000,-2.057232,...,0.500000,6.958981,3.243496,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28123,2025-04-25 13:48:09,2025-04-25 13:48:09,IR_60094.jpg,7,Cableduct,Cableduct,cableduct_2,21.778038,28.000000,-2.037811,...,0.500000,6.340442,2.364851,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28218,2025-04-25 13:53:39,2025-04-25 13:53:39,IR_60105.jpg,3,Cableduct,Cableduct,cableduct_2,23.201733,28.700001,1.915190,...,0.500000,7.109313,3.300023,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28370,2025-04-25 14:02:09,2025-04-25 14:02:09,IR_60122.jpg,5,Cableduct,Cableduct,cableduct_2,22.300100,27.299999,-1.896063,...,0.500000,7.290601,3.333649,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27591,2025-04-25 13:13:09,2025-04-25 13:13:09,IR_60024.jpg,9,Cableduct,Cableduct,cableduct_2,22.691139,27.700001,-1.888554,...,3.000000,7.026527,3.231216,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27916,2025-04-25 13:34:39,2025-04-25 13:34:39,IR_60067.jpg,8,Cableduct,Cableduct,cableduct_2,21.914469,28.500000,-1.884315,...,0.500000,6.076321,2.310606,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
24726,2025-04-25 10:27:38,2025-04-25 10:27:38,IR_59693.jpg,3,Cableduct,Cableduct,cableduct_2,21.146221,23.700001,-1.860640,...,0.483333,7.345599,3.343233,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
24109,2025-04-25 09:52:39,2025-04-25 09:52:39,IR_59623.jpg,5,Cableduct,Cableduct,cableduct_2,20.961470,23.500000,-1.853210,...,0.500000,7.424008,3.371017,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28009,2025-04-25 13:41:09,2025-04-25 13:41:09,IR_60080.jpg,7,Cableduct,Cableduct,cableduct_2,23.272186,29.700001,1.828443,...,0.500000,7.131481,3.269723,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27552,2025-04-25 13:10:09,2025-04-25 13:10:09,IR_60018.jpg,4,Cableduct,Cableduct,cableduct_2,24.579693,33.299999,1.801329,...,1.516667,6.891170,3.194609,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28481,2025-04-25 14:09:08,2025-04-25 14:09:08,IR_60136.jpg,8,Cableduct,Cableduct,cableduct_2,21.422058,24.100000,-1.662489,...,0.483333,7.359851,3.340472,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27878,2025-04-25 13:32:38,2025-04-25 13:32:38,IR_60063.jpg,11,Cableduct,Cableduct,cableduct_2,24.575544,28.400000,1.643041,...,0.000000,6.336694,2.242172,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28733,2025-04-25 14:23:39,2025-04-25 14:23:39,IR_60165.jpg,7,Cableduct,Cableduct,cableduct_2,21.300962,24.000000,-1.624821,...,0.500000,7.330554,3.370467,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27529,2025-04-25 13:08:09,2025-04-25 13:08:09,IR_60014.jpg,6,Cableduct,Cableduct,cableduct_2,21.906839,29.299999,-1.601027,...,0.500000,5.693965,2.297709,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
23728,2025-04-25 09:33:39,2025-04-25 09:33:39,IR_59585.jpg,9,Cableduct,Cableduct,cableduct_2,20.691355,26.200001,-1.575008,...,0.500000,7.141988,3.310433,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28669,2025-04-25 14:19:39,2025-04-25 14:19:39,IR_60157.jpg,9,Cableduct,Cableduct,cableduct_2,22.167925,27.500000,-1.564505,...,0.000000,7.223205,3.312559,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
23766,2025-04-25 09:35:39,2025-04-25 09:35:39,IR_59589.jpg,11,Cableduct,Cableduct,cableduct_2,21.368914,27.000000,-1.544763,...,0.000000,8.743574,2.909510,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
26942,2025-04-25 12:32:09,2025-04-25 12:32:09,IR_59942.jpg,7,Cableduct,Cableduct,cableduct_2,23.939621,33.200001,1.503532,...,1.000000,7.199069,3.289493,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
23739,2025-04-25 09:34:09,2025-04-25 09:34:09,IR_59586.jpg,3,Cableduct,Cableduct,cableduct_2,22.172518,26.500000,1.481163,...,0.500000,6.979826,3.216818,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
23624,2025-04-25 09:28:39,2025-04-25 09:28:39,IR_59575.jpg,8,Cableduct,Cableduct,cableduct_2,22.534868,30.000000,1.429842,...,0.500000,7.261063,3.310460,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct

Hottest rows:

,timestamp_dt,timestamp,image_name,detection_index,label,canonical_label,object_id,temp_mean_c,temp_max_c,temp_delta_c,...,gap_min,projected_x,projected_y,anchor_x,anchor_y,display_x,display_y,position_source,static_cluster_id,clustering_method
28010,2025-04-25 13:41:09,2025-04-25 13:41:09,IR_60080.jpg,10,Cableduct,Cableduct,cableduct_2,24.697624,29.700001,1.425438,...,0.000000,5.227508,2.294672,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27552,2025-04-25 13:10:09,2025-04-25 13:10:09,IR_60018.jpg,4,Cableduct,Cableduct,cableduct_2,24.579693,33.299999,1.801329,...,1.516667,6.891170,3.194609,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27878,2025-04-25 13:32:38,2025-04-25 13:32:38,IR_60063.jpg,11,Cableduct,Cableduct,cableduct_2,24.575544,28.400000,1.643041,...,0.000000,6.336694,2.242172,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27799,2025-04-25 13:27:38,2025-04-25 13:27:38,IR_60053.jpg,6,Cableduct,Cableduct,cableduct_2,24.558969,33.200001,2.443660,...,0.500000,7.338344,3.350806,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28199,2025-04-25 13:52:38,2025-04-25 13:52:38,IR_60103.jpg,10,Cableduct,Cableduct,cableduct_2,24.455154,27.799999,2.067308,...,0.000000,6.356072,2.256669,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28361,2025-04-25 14:01:39,2025-04-25 14:01:39,IR_60121.jpg,7,Cableduct,Cableduct,cableduct_2,24.196163,29.299999,0.833156,...,0.000000,7.481864,2.486051,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28046,2025-04-25 13:43:09,2025-04-25 13:43:09,IR_60084.jpg,11,Cableduct,Cableduct,cableduct_2,24.118624,28.200001,1.088661,...,0.000000,7.287808,2.484919,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27602,2025-04-25 13:13:39,2025-04-25 13:13:39,IR_60025.jpg,10,Cableduct,Cableduct,cableduct_2,24.016699,28.100000,1.252581,...,0.000000,5.085540,2.216485,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
26942,2025-04-25 12:32:09,2025-04-25 12:32:09,IR_59942.jpg,7,Cableduct,Cableduct,cableduct_2,23.939621,33.200001,1.503532,...,1.000000,7.199069,3.289493,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28119,2025-04-25 13:47:39,2025-04-25 13:47:39,IR_60093.jpg,4,Cableduct,Cableduct,cableduct_2,23.815849,33.900002,0.684175,...,0.500000,7.194311,3.311062,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28698,2025-04-25 14:21:39,2025-04-25 14:21:39,IR_60161.jpg,6,Cableduct,Cableduct,cableduct_2,23.811113,32.099998,1.220199,...,0.516667,7.216233,3.304722,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27905,2025-04-25 13:34:09,2025-04-25 13:34:09,IR_60066.jpg,13,Cableduct,Cableduct,cableduct_2,23.798784,27.799999,1.199045,...,0.000000,5.771558,2.295064,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28668,2025-04-25 14:19:39,2025-04-25 14:19:39,IR_60157.jpg,6,Cableduct,Cableduct,cableduct_2,23.732430,27.500000,1.296446,...,0.500000,5.225345,2.243522,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28277,2025-04-25 13:57:08,2025-04-25 13:57:08,IR_60112.jpg,9,Cableduct,Cableduct,cableduct_2,23.644718,27.299999,0.250723,...,0.000000,6.387563,2.406792,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28140,2025-04-25 13:49:09,2025-04-25 13:49:09,IR_60096.jpg,10,Cableduct,Cableduct,cableduct_2,23.619781,27.500000,1.126476,...,0.000000,1.491920,1.125904,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
26973,2025-04-25 12:34:39,2025-04-25 12:34:39,IR_59947.jpg,8,Cableduct,Cableduct,cableduct_2,23.591326,32.500000,0.900301,...,0.000000,7.033350,3.262479,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
24182,2025-04-25 09:56:39,2025-04-25 09:56:39,IR_59631.jpg,7,Cableduct,Cableduct,cableduct_2,23.555708,27.100000,1.255255,...,0.000000,6.067247,2.385044,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27520,2025-04-25 13:07:39,2025-04-25 13:07:39,IR_60013.jpg,9,Cableduct,Cableduct,cableduct_2,23.507866,27.799999,1.017601,...,0.000000,4.842773,2.220070,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
24202,2025-04-25 09:57:39,2025-04-25 09:57:39,IR_59633.jpg,10,Cableduct,Cableduct,cableduct_2,23.487612,27.200001,1.138304,...,0.000000,7.991884,2.517294,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
23740,2025-04-25 09:34:09,2025-04-25 09:34:09,IR_59586.jpg,8,Cableduct,Cableduct,cableduct_2,23.453957,26.500000,1.281439,...,0.000000,5.252523,2.262696,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
24556,2025-04-25 10:17:39,2025-04-25 10:17:39,IR_59673.jpg,5,Cableduct,Cableduct,cableduct_2,23.445864,26.600000,2.079485,...,0.500000,4.810170,2.207242,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28463,2025-04-25 14:08:09,2025-04-25 14:08:09,IR_60134.jpg,11,Cableduct,Cableduct,cableduct_2,23.416651,27.400000,1.208018,...,0.000000,5.068931,2.287247,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28276,2025-04-25 13:57:08,2025-04-25 13:57:08,IR_60112.jpg,4,Cableduct,Cableduct,cableduct_2,23.393995,27.299999,1.172863,...,0.483333,7.232728,3.375040,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28141,2025-04-25 13:49:09,2025-04-25 13:49:09,IR_60096.jpg,11,Cableduct,Cableduct,cableduct_2,23.375301,27.500000,-0.244480,...,0.000000,3.611470,1.808765,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28354,2025-04-25 14:01:09,2025-04-25 14:01:09,IR_60120.jpg,8,Cableduct,Cableduct,cableduct_2,23.366449,27.700001,0.544605,...,0.000000,4.859449,2.266861,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28360,2025-04-25 14:01:39,2025-04-25 14:01:39,IR_60121.jpg,5,Cableduct,Cableduct,cableduct_2,23.363007,29.299999,-0.003442,...,0.500000,7.024296,3.220993,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
26827,2025-04-25 12:22:09,2025-04-25 12:22:09,IR_59922.jpg,7,Cableduct,Cableduct,cableduct_2,23.360786,30.799999,1.344604,...,1.000000,7.246542,3.334298,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28219,2025-04-25 13:53:39,2025-04-25 13:53:39,IR_60105.jpg,8,Cableduct,Cableduct,cableduct_2,23.310925,28.700001,0.109192,...,0.000000,9.167489,2.196785,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27806,2025-04-25 13:28:09,2025-04-25 13:28:09,IR_60054.jpg,10,Cableduct,Cableduct,cableduct_2,23.278528,28.500000,-1.280441,...,0.516667,6.900939,3.184920,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28009,2025-04-25 13:41:09,2025-04-25 13:41:09,IR_60080.jpg,7,Cableduct,Cableduct,cableduct_2,23.272186,29.700001,1.828443,...,0.500000,7.131481,3.269723,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct

In [6]:
# Duplicate timestamp check: multiple rows for the same object and timestamp can create noisy GT curves later.
duplicate_groups = (
    object_day
    .groupby('timestamp_dt')
    .size()
    .reset_index(name='rows_at_timestamp')
    .query('rows_at_timestamp > 1')
    .sort_values('rows_at_timestamp', ascending=False)
)
print(f"Duplicate timestamps for {DEBUG_OBJECT_ID} on {DEBUG_DATE}: {len(duplicate_groups)}")
display(duplicate_groups.head(DEBUG_TOP_N))

if not duplicate_groups.empty:
    duplicated_rows = object_day[object_day['timestamp_dt'].isin(duplicate_groups['timestamp_dt'])].copy()
    duplicated_rows = duplicated_rows.sort_values(['timestamp_dt', 'detection_index'])
    duplicate_display_cols = [col for col in inspect_cols if col in duplicated_rows.columns]
    display(duplicated_rows[duplicate_display_cols].head(DEBUG_TOP_N * 3))

Duplicate timestamps for cableduct_2 on 2025-04-25: 63

           timestamp_dt  rows_at_timestamp
676 2025-04-25 13:49:09                  3
682 2025-04-25 13:53:39                  3
237 2025-04-25 09:35:39                  3
2   2025-04-25 07:37:09                  2
629 2025-04-25 13:07:39                  2
652 2025-04-25 13:32:38                  2
634 2025-04-25 13:13:39                  2
630 2025-04-25 13:08:09                  2
628 2025-04-25 13:06:39                  2
662 2025-04-25 13:41:09                  2
627 2025-04-25 13:06:09                  2
614 2025-04-25 12:59:39                  2
590 2025-04-25 12:46:38                  2
584 2025-04-25 12:43:39                  2
571 2025-04-25 12:34:39                  2
567 2025-04-25 12:31:09                  2
654 2025-04-25 13:34:09                  2
667 2025-04-25 13:44:09                  2
665 2025-04-25 13:43:09                  2
563 2025-04-25 12:27:39                  2
674 2025-04-25 13:48:09                  2
680 2025-04-25 13:52:38                  2
689 2025-04-25 13:57:08                  2
692 2025-04-25 13:58:39                  2
693 2025-04-25 13:59:08                  2
697 2025-04-25 14:01:09                  2
698 2025-04-25 14:01:39                  2
707 2025-04-25 14:07:09                  2
708 2025-04-25 14:07:39                  2
709 2025-04-25 14:08:09                  2

,timestamp_dt,timestamp,image_name,detection_index,label,canonical_label,object_id,temp_mean_c,temp_max_c,temp_delta_c,...,gap_min,projected_x,projected_y,anchor_x,anchor_y,display_x,display_y,position_source,static_cluster_id,clustering_method
21314,2025-04-25 07:37:09,2025-04-25 07:37:09,IR_59352.jpg,7,Cableduct,Cableduct,cableduct_2,19.719055,22.400000,-0.273522,...,0.500000,9.218672,3.074748,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
21315,2025-04-25 07:37:09,2025-04-25 07:37:09,IR_59352.jpg,11,Cableduct,Cableduct,cableduct_2,20.003307,22.400000,0.284252,...,0.000000,6.837590,3.156633,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
22847,2025-04-25 08:50:39,2025-04-25 08:50:39,IR_59499.jpg,8,Cableduct,Cableduct,cableduct_2,21.131323,24.000000,0.079388,...,0.500000,7.222908,3.324115,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
22848,2025-04-25 08:50:39,2025-04-25 08:50:39,IR_59499.jpg,11,Cableduct,Cableduct,cableduct_2,20.853014,24.000000,-0.278309,...,0.000000,5.622603,2.352094,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
22890,2025-04-25 08:52:39,2025-04-25 08:52:39,IR_59503.jpg,5,Cableduct,Cableduct,cableduct_2,21.398756,26.500000,0.148108,...,0.500000,7.232780,3.318498,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27529,2025-04-25 13:08:09,2025-04-25 13:08:09,IR_60014.jpg,6,Cableduct,Cableduct,cableduct_2,21.906839,29.299999,-1.601027,...,0.500000,5.693965,2.297709,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27530,2025-04-25 13:08:09,2025-04-25 13:08:09,IR_60014.jpg,9,Cableduct,Cableduct,cableduct_2,22.562540,29.299999,0.655701,...,0.000000,7.251842,3.328636,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27601,2025-04-25 13:13:39,2025-04-25 13:13:39,IR_60025.jpg,3,Cableduct,Cableduct,cableduct_2,22.764118,28.100000,0.072979,...,0.500000,6.768492,3.153079,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27602,2025-04-25 13:13:39,2025-04-25 13:13:39,IR_60025.jpg,10,Cableduct,Cableduct,cableduct_2,24.016699,28.100000,1.252581,...,0.000000,5.085540,2.216485,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27877,2025-04-25 13:32:38,2025-04-25 13:32:38,IR_60063.jpg,10,Cableduct,Cableduct,cableduct_2,22.932503,28.400000,-0.010753,...,1.483333,6.984655,3.214825,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct

In [7]:
# Trace the selected object/date back to the 05 integrated CSV.
integrated_debug = pd.read_csv(config.INTEGRATED_OBJECTS_CSV)
integrated_debug['timestamp_dt'] = pd.to_datetime(integrated_debug['timestamp'])
integrated_debug = integrated_debug[
    (integrated_debug['object_id'] == DEBUG_OBJECT_ID) &
    (integrated_debug['timestamp_dt'].dt.date.astype(str) == DEBUG_DATE)
].copy()
for column in ['temp_mean_c', 'temp_max_c', 'projected_x', 'projected_y', 'anchor_x', 'anchor_y']:
    if column in integrated_debug.columns:
        integrated_debug[column] = pd.to_numeric(integrated_debug[column], errors='coerce')

print(f"Integrated rows for {DEBUG_DATE} | {DEBUG_OBJECT_ID}: {len(integrated_debug)}")
label_summary = (
    integrated_debug
    .groupby(['label', 'canonical_label', 'position_source', 'clustering_method'], dropna=False)
    .size()
    .reset_index(name='rows')
    .sort_values('rows', ascending=False)
)
display(label_summary)

integrated_cols = [
    'timestamp', 'image_name', 'detection_index', 'label', 'canonical_label', 'object_id',
    'temp_mean_c', 'temp_max_c', 'projected_x', 'projected_y', 'anchor_x', 'anchor_y',
    'display_x', 'display_y', 'position_source', 'static_cluster_id', 'clustering_method',
]
integrated_cols = [col for col in integrated_cols if col in integrated_debug.columns]
print('Integrated hottest rows:')
display(integrated_debug.sort_values('temp_mean_c', ascending=False)[integrated_cols].head(DEBUG_TOP_N))

Integrated rows for 2025-04-25 | cableduct_2: 964

,label,canonical_label,position_source,clustering_method,rows
0,Cableduct,Cableduct,dbscan_cableduct_global_median_anchor,dbscan_cableduct,862
1,Cableduct,Cableduct,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct,102

Integrated hottest rows:

,timestamp,image_name,detection_index,label,canonical_label,object_id,temp_mean_c,temp_max_c,projected_x,projected_y,anchor_x,anchor_y,display_x,display_y,position_source,static_cluster_id,clustering_method
28010,2025-04-25 13:41:09,IR_60080.jpg,10,Cableduct,Cableduct,cableduct_2,24.697624,29.700001,5.227508,2.294672,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27552,2025-04-25 13:10:09,IR_60018.jpg,4,Cableduct,Cableduct,cableduct_2,24.579693,33.299999,6.891170,3.194609,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27878,2025-04-25 13:32:38,IR_60063.jpg,11,Cableduct,Cableduct,cableduct_2,24.575544,28.400000,6.336694,2.242172,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27799,2025-04-25 13:27:38,IR_60053.jpg,6,Cableduct,Cableduct,cableduct_2,24.558969,33.200001,7.338344,3.350806,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28199,2025-04-25 13:52:38,IR_60103.jpg,10,Cableduct,Cableduct,cableduct_2,24.455154,27.799999,6.356072,2.256669,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28361,2025-04-25 14:01:39,IR_60121.jpg,7,Cableduct,Cableduct,cableduct_2,24.196163,29.299999,7.481864,2.486051,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28046,2025-04-25 13:43:09,IR_60084.jpg,11,Cableduct,Cableduct,cableduct_2,24.118624,28.200001,7.287808,2.484919,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27602,2025-04-25 13:13:39,IR_60025.jpg,10,Cableduct,Cableduct,cableduct_2,24.016699,28.100000,5.085540,2.216485,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
26942,2025-04-25 12:32:09,IR_59942.jpg,7,Cableduct,Cableduct,cableduct_2,23.939621,33.200001,7.199069,3.289493,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28119,2025-04-25 13:47:39,IR_60093.jpg,4,Cableduct,Cableduct,cableduct_2,23.815849,33.900002,7.194311,3.311062,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28698,2025-04-25 14:21:39,IR_60161.jpg,6,Cableduct,Cableduct,cableduct_2,23.811113,32.099998,7.216233,3.304722,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
27905,2025-04-25 13:34:09,IR_60066.jpg,13,Cableduct,Cableduct,cableduct_2,23.798784,27.799999,5.771558,2.295064,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28668,2025-04-25 14:19:39,IR_60157.jpg,6,Cableduct,Cableduct,cableduct_2,23.732430,27.500000,5.225345,2.243522,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28277,2025-04-25 13:57:08,IR_60112.jpg,9,Cableduct,Cableduct,cableduct_2,23.644718,27.299999,6.387563,2.406792,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28140,2025-04-25 13:49:09,IR_60096.jpg,10,Cableduct,Cableduct,cableduct_2,23.619781,27.500000,1.491920,1.125904,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
26973,2025-04-25 12:34:39,IR_59947.jpg,8,Cableduct,Cableduct,cableduct_2,23.591326,32.500000,7.033350,3.262479,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
24182,2025-04-25 09:56:39,IR_59631.jpg,7,Cableduct,Cableduct,cableduct_2,23.555708,27.100000,6.067247,2.385044,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27520,2025-04-25 13:07:39,IR_60013.jpg,9,Cableduct,Cableduct,cableduct_2,23.507866,27.799999,4.842773,2.220070,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
24202,2025-04-25 09:57:39,IR_59633.jpg,10,Cableduct,Cableduct,cableduct_2,23.487612,27.200001,7.991884,2.517294,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
23740,2025-04-25 09:34:09,IR_59586.jpg,8,Cableduct,Cableduct,cableduct_2,23.453957,26.500000,5.252523,2.262696,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
24556,2025-04-25 10:17:39,IR_59673.jpg,5,Cableduct,Cableduct,cableduct_2,23.445864,26.600000,4.810170,2.207242,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28463,2025-04-25 14:08:09,IR_60134.jpg,11,Cableduct,Cableduct,cableduct_2,23.416651,27.400000,5.068931,2.287247,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28276,2025-04-25 13:57:08,IR_60112.jpg,4,Cableduct,Cableduct,cableduct_2,23.393995,27.299999,7.232728,3.375040,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28141,2025-04-25 13:49:09,IR_60096.jpg,11,Cableduct,Cableduct,cableduct_2,23.375301,27.500000,3.611470,1.808765,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28354,2025-04-25 14:01:09,IR_60120.jpg,8,Cableduct,Cableduct,cableduct_2,23.366449,27.700001,4.859449,2.266861,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
28360,2025-04-25 14:01:39,IR_60121.jpg,5,Cableduct,Cableduct,cableduct_2,23.363007,29.299999,7.024296,3.220993,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
26827,2025-04-25 12:22:09,IR_59922.jpg,7,Cableduct,Cableduct,cableduct_2,23.360786,30.799999,7.246542,3.334298,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28219,2025-04-25 13:53:39,IR_60105.jpg,8,Cableduct,Cableduct,cableduct_2,23.310925,28.700001,9.167489,2.196785,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_nearest_same_label_anchor,dbscan_cableduct_0000,dbscan_cableduct
27806,2025-04-25 13:28:09,IR_60054.jpg,10,Cableduct,Cableduct,cableduct_2,23.278528,28.500000,6.900939,3.184920,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct
28009,2025-04-25 13:41:09,IR_60080.jpg,7,Cableduct,Cableduct,cableduct_2,23.272186,29.700001,7.131481,3.269723,7.344941,3.358257,7.344941,3.358257,dbscan_cableduct_global_median_anchor,dbscan_cableduct_0000,dbscan_cableduct